### ISSUE TITLE
The action you have requested is not allowed.

### ISSUE THREAD

**Issue by mecmav** [mateusznitka/protocolsmanager#1]
In Administration > Profiles > Any profile

When mark/unmark to set options to profiles, have an error from GLPI "The action you have requested is not allowed.". But the action is applied.
![print](https://user-images.githubusercontent.com/37091495/73127274-54e19100-3f94-11ea-8984-f5f97385a21a.jpg)

**Comment by mateusznitka** [comment]
I can't reproduce this error. Do you get this message every time? What is your active profile? Super-admin? Does this message appear after mark / unmark the checkbox or after pressing "save" button?
Regards, 
Mat

**Comment by mecmav** [comment]
Sorry, I think I done something wrong. Close this issue.
