### ISSUE TITLE
error when creating the document

### ISSUE THREAD

**Issue by guillermohaad** [mateusznitka/protocolsmanager#10]
Hello friend, I want to congratulate you for such an excellent job, I will give you for many cafes my friend if it works for me. I have the following message when I try to create the document.

File /var/www/html/glpi/files/_tmp/4-03032020.pdf not found

version  GLPI 9.3.1  and plugin protocolsmanager 1.2 

![image](https://user-images.githubusercontent.com/12921805/75820941-52304380-5d6b-11ea-9532-3782f0360e8e.png)

**Comment by guillermohaad** [comment]
Hello friend,
How can I save custom fields?

![image](https://user-images.githubusercontent.com/12921805/75821277-f4e8c200-5d6b-11ea-9dc5-6e4a7f3fb9e0.png)

**Comment by mateusznitka** [comment]
Hi @guillermohaad 
As I wrote in readme, in GLPI 9.3 you have to edit protocolsmanager/inc/**generate.class.php** file: 
change **GLPI_UPLOAD_DIR** to **GLPI_TMP_DIR**
it is in line 365:
$html2pdf->Output(GLPI_UPLOAD_DIR .'/'.$doc_name, 'F');

so edit it to:

$html2pdf->Output(GLPI_TMP_DIR .'/'.$doc_name, 'F');

About your second question:
Custom rows are temporary for each export. So if you fill custom inputs like on your screenshot and generate protocol, it will be saved in PDF.

**Comment by guillermohaad** [comment]
hi @mateusznitka  Thanks for your help, it was corrected but now it doesn't show me the related equipment
![image](https://user-images.githubusercontent.com/12921805/75822850-abe63d00-5d6e-11ea-81bb-f23c4c94538b.png)

**Comment by mateusznitka** [comment]
Did you select checkboxes for items? Before generate you have to select what items you want to have on protocol.

**Comment by guillermohaad** [comment]
Thank you, my friend, how big you are, you earned a coffee in my name, I recommend you save the custom field in the next versions to be able to generate at any time. but excellent work.
Thank you for making our lives easier.
