### ISSUE TITLE
Display assets from other plugins

### ISSUE THREAD

**Issue by zamach132** [mateusznitka/protocolsmanager#12]
Hi there, 
Is there any way to display assets from genericobcject plugin ?

**Comment by mateusznitka** [comment]
Hi, 
They should be visible from Protocols Manager. 
I'm using genericobject and simcards plugin and it works fine.
What is your version of glpi and genericobject plugin? Do you have user assigend to your object?

Regards

**Comment by zamach132** [comment]
It was my mistake, 
Everything works fine. Thenks a lot for usefull plugin.
