### ISSUE TITLE
Problem with punctuation in slovak language

### ISSUE THREAD

**Issue by PeterKarvai-ROEZ** [mateusznitka/protocolsmanager#16]
Hi, 
As you see on picture below, some characters with punnctation are changed to question mark symbol in generated protocol.
Example: "ľ" changed to "?" 

![tempsnip](https://user-images.githubusercontent.com/66006347/87398057-a539c300-c5b5-11ea-87c9-7ff37b744ede.png)

How can I solve this please?

Thank you,
Regards

**Comment by mateusznitka** [comment]
Hi, Please check other fonts (Roboto, Istok, DroidSerif or DejaVuSans for example). Times New Roman in domPDF doesn't have polish letters so it can be problem with slovak too, but I preinstalled few other TTF fonts and it should work with slavic languages.

Regards
