### ISSUE TITLE
Forms Creator is interfering with the Radio buttons of Protocolsmanager plugin and its interface.

### ISSUE THREAD

**Issue by jcervantes-sipecom** [mateusznitka/protocolsmanager#17]
Hi, I opened a issue in Form Creator, because it seems that being active it interferes with the interface of Protocolsmanager and another plugin, making the Radio Buttons disappear, this is the open ISSUE: [formcreator/#2009](https://github.com/pluginsGLPI/formcreator/issues/2009)

Basically this happens:

**Screenshots**
- When Forms creator is **disabled:**

> - Protocolsmanager:
![image](https://user-images.githubusercontent.com/56606032/99086561-b1e81b00-2597-11eb-8347-b888668f7626.png)
![image](https://user-images.githubusercontent.com/56606032/99086592-bc0a1980-2597-11eb-9623-670e5cf4cb53.png)

**In this part I can edit everything**

> ![image](https://user-images.githubusercontent.com/56606032/99086615-c4faeb00-2597-11eb-8576-53a0f7c574a3.png)

**As you can see the radio buttons on the plugins is visible, and in the send email screen for Protocolsmanager I can edit it**

- But when Form Creator is **enabled:**

> - Protocolsmanager:
![image](https://user-images.githubusercontent.com/56606032/99087158-713cd180-2598-11eb-85fe-e07decf550a1.png)
![image](https://user-images.githubusercontent.com/56606032/99087205-7ef25700-2598-11eb-9bc2-17a51341954b.png)

**In this part I cannot edit nothing**

> ![image](https://user-images.githubusercontent.com/56606032/99087289-96c9db00-2598-11eb-8a7b-3f7131a7b41f.png)

**As you can see the radio buttons on the plugin is invisible or not displayed, and in the send email screen for Protocolsmanager I cannot edit it**

I don't know exactly what the problem would be so I inform the 2 plugins.

**Comment by mateusznitka** [comment]
Hi,
Thanks for using my plugin. As I see, problem is resolved in Form Creator plugin so I close the ticket.
https://github.com/pluginsGLPI/formcreator/issues/2009

Regards
