### ISSUE TITLE
Emails are sent with no attachments

### ISSUE THREAD

**Issue by patriciocs1979** [mateusznitka/protocolsmanager#22]
Hello,

Thanks for this excellent plugin. It works very well, however I have not managed to make it send e-mails notifications with the created PDF attached to it. There is no error message, it just send the e-mail but it doesn't have the protocol PDF document attached. The e-mail is correctly sent to all recipients with the correct subject and e-mail body.

I am using GLPI 9.5.2 and the last version of protocolsmanager. I don't know what log file should I attach in order for you to address the issue.

![image](https://user-images.githubusercontent.com/23280231/105212604-7421e880-5b2c-11eb-9cae-76732fc0cdc7.png)

e-mail settings:
![image](https://user-images.githubusercontent.com/23280231/105212741-99aef200-5b2c-11eb-9261-2d6506997fe2.png)

Template settings:
![image](https://user-images.githubusercontent.com/23280231/105212812-b0554900-5b2c-11eb-8a87-81f0a47a83a4.png)

The e-mail I receive:
![image](https://user-images.githubusercontent.com/23280231/105212924-d0850800-5b2c-11eb-9dd4-e9a4227aefa7.png)

Please let me know if you need something else. Best regards and thanks in advance.

**Comment by mateusznitka** [comment]
Hi,
One check: is your image (logo) showed in protocol?

Please try change line 555 and 671 in inc/generate.class.php:
from:
`$fullpath = GLPI_ROOT."/files/".$path;`

to:
`$fullpath =  "/var/lib/glpi/files/".$path;`


Let me know if it help or not.

Regards,
Mat

**Comment by patriciocs1979** [comment]
Hi, thanks for your response. Yes the logo is showed in the generated PDF protocol document.

 

After modifying the lines the problem is solved now. Thank you very much!!!!!!

 

De: Mateusz Nitka <notifications@github.com> 
Enviado el: miércoles, 20 de enero de 2021 14:50
Para: mateusznitka/protocolsmanager <protocolsmanager@noreply.github.com>
CC: patriciocs1979 <patriciocs@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [mateusznitka/protocolsmanager] Emails are sent with no attachments (#22)

 

Hi,
One check: is your image (logo) showed in protocol?

Please try change line 555 and 671 in inc/generate.class.php:
from:
$fullpath = GLPI_ROOT."/files/".$path;

to:
$fullpath = "/var/lib/glpi/files/".$path;

Let me know if it help or not.

Regards,
Mat
