### ISSUE TITLE
Error in Logo: Image not found or type unknown

### ISSUE THREAD

**Issue by blitzlepe** [mateusznitka/protocolsmanager#25]
Image logo is not even shown in the template form:
My setup GLPI 9.5.4 
PHP 7.3.27
Centos 8

![image](https://user-images.githubusercontent.com/73666581/112667605-1313db00-8e23-11eb-9dd8-e7ca5d410277.png)

![image](https://user-images.githubusercontent.com/73666581/112667679-2e7ee600-8e23-11eb-92e6-32b4f9817005.png)

**Comment by mateusznitka** [comment]
Hi,
I think there is maybe problem with GLPI_ROOT variable, so image pointing to wrong path. Try change:
**In inc/config.php.class**
Line 188 - from $full_img_name = GLPI_ROOT.'/files/_pictures/'.$logo;
to $full_img_name = '/var/lib/glpi/files/_pictures/'.$logo;

Line 524 - from $img_path = GLPI_ROOT.'/files/_pictures/'.$full_img_name;
to $img_path = '/var/lib/glpi/files/_pictures/'.$full_img_name;

**In inc/generate.class.php:**
Line 440 - from $logo = GLPI_ROOT.'/files/_pictures/'.$full_img_name;
to $logo = 'var/lib/glpi/files/_pictures/'.$full_img_name;

Of course change paths to your installation, but usually there are like I wrote.

Regards,
MN

**Comment by blitzlepe** [comment]
Solved with that lines replaced.

Thank you!
