### ISSUE TITLE
Not generating

### ISSUE THREAD

**Issue by Skiller899** [mateusznitka/protocolsmanager#29]
Hello, I today found this very nice plugin, but it doesn´t work. I tried default template and new one. But still not works. After I pick user and pick item from table and click to create it open url ...../plugins/protocolsmanager/front/generate.form.php and this is all. White screen and nothing happens. Can you help me please?

**Comment by Skiller899** [comment]
Glpi version 9.4.4
PHP version 5.6.40
Parse error: syntax error, unexpected '=' in /var/www/html/glpi/plugins/protocolsmanager/dompdf/src/Dompdf.php on line 356

**Comment by mateusznitka** [comment]
Like I wrote in readme:

> 
> Compatibility
> GLPI 9.3 or higher PHP 7.1 or higher

You have to update your php version, PHP 7.1 is requirement for dompdf library which I using in this project.

**Comment by mateusznitka** [comment]
Are you sure that you switched to new version after update? What version of php is in Server section in GLPI -> Setup -> General -> System?

**Comment by Skiller899** [comment]
Oukey, thanks. It works. I am only stupid... :( Thumbs up for you

**Comment by mateusznitka** [comment]
Nice to see that it works, hope plugin will be useful.
