### ISSUE TITLE
GLPI v10

### ISSUE THREAD

**Issue by Alexk05m** [mateusznitka/protocolsmanager#45]
Hello,

Could you add compatibility for glpi v10 and php 7.4 ?

**Comment by daviox** [comment]
I'd be more than happy if I'll be able to continue using this plugin in v10

**Comment by Wolvverine** [comment]
@daviox 

Look to my repositories, you have last patched version.

**Comment by Alexk05m** [comment]
@Wolvverine 

I use your last patched version but I still have access denied

**Comment by Wolvverine** [comment]
Which branch?

Look on develop-v10

**Comment by Alexk05m** [comment]
I just did a test with a new installation (debian 10 - GLPI v10 - php7.4) and the develop-v10 branch but I have an error message when I install the plugin :

`- Erreur durant l'éxecution de la requête : ALTER TABLE glpi_plugin_protocolsmanager_emailconfig MODIFY COLUMN email_content TEXT - L'erreur est Table 'db_glpi.glpi_plugin_protocolsmanager_emailconfig' doesn't exist`

**Comment by MC-brunomendes** [comment]
Yes the access denied message also affects me... Can't really test if you repo works @Wolvverine since this is blocking the usage.

Would be glad on helping developing but not very expert on php

**Comment by LuizRicarte** [comment]
@Wolvverine 

After downloading develo-10, performing the installation, it displays the message of access denied.
Can you help me?
![image](https://user-images.githubusercontent.com/104385269/165389000-2b567b3c-f53c-402a-ba95-413eb821134c.png)

**Comment by LuizRicarte** [comment]
@Wolvverine in line 157?
Not effect to me, still access denied.

**Comment by LuizRicarte** [comment]
@Wolvverine Dou you Help Me?

![image](https://user-images.githubusercontent.com/104385269/166831841-fda00b9e-7d19-4f4e-85a5-0c55bffbae2e.png)

**Comment by Wolvverine** [comment]
Check now, and I will add new dompdf  but in other branch.

**Comment by Alexk05m** [comment]
@Wolvverine 

Thank you for the time spent, on my side it works perfectly with branch (develop-v10-dompdf)!

thanks again

**Comment by Wolvverine** [comment]
@LuizRicarte @MC-brunomendes @daviox ?

**Comment by pistokcad** [comment]
> @LuizRicarte @MC-brunomendes @daviox @Dayflare @pistokcad ?

I don't have any issue (your modification good) - I written another topic.

**Comment by daviox** [comment]
I'll check the updates as soon as I'll be able to.

I guess that will do it, since I too have a problem with permissions.

**Comment by MC-brunomendes** [comment]
@Wolvverine repo with dompdf works great on 10.0

**Comment by Dayflare** [comment]
> @LuizRicarte @MC-brunomendes @daviox @Dayflare @pistokcad ?

i'll check soon with the new 10.0.1 version of GLPI

**Comment by Dayflare** [comment]
> @LuizRicarte @MC-brunomendes @daviox @Dayflare @pistokcad ?

runs great on GLPI 10.0.1, having a few issues with the image in the header of the pdf, but beside of this it's running good and everything works.
a big thanks for your work!
