### ISSUE TITLE
Undefined variable $containerName in generate.class.php

### ISSUE THREAD

**Issue by Jasiopi** [mateusznitka/protocolsmanager#61]
Hello, I install this plugin, and when I go to Administration/users and in users open tab with Protocol Menager I see this warning.

Warning: Undefined variable $containerName in C:\xampp\htdocs\glpi\plugins\protocolsmanager\inc\generate.class.php on line 134

<img width="734" alt="image" src="https://user-images.githubusercontent.com/104274172/219015741-7e3e466b-42e7-40a7-acf7-374e36b1d1f4.png">

<img width="881" alt="image" src="https://user-images.githubusercontent.com/104274172/219015888-e2388579-1d8d-46fc-b02a-1091c75e4017.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/104274172/219015994-96d307ed-723b-4493-850c-6ef46ef1aaaf.png">

I don`t know what a heppen.

**Comment by pistokcad** [comment]
Please check the PHP version.
As I know the PHP 7.4 the good version. (In the version 8 generate lot of misterious error message)

**Comment by Jasiopi** [comment]
You has right. I have GLPI on PHP 8.2.0
You can have maby idea, what i can do with this?

**Comment by Jasiopi** [comment]
You has right. I have GLPI with PHP 8.2.0
You has any idea What I can do with this?

**Comment by pistokcad** [comment]
> You has right. I have GLPI with PHP 8.2.0 You has any idea What I can do with this?

Install a good version of PHP.
