### ISSUE TITLE
no text wrapping when column is too small for single words too long

### ISSUE THREAD

**Issue by Giudy** [mateusznitka/protocolsmanager#8]
Hello, if a field contain a single word that is longer than width of a column, there no text wrapping and the text goes over the following columns and their contents.
![image](https://user-images.githubusercontent.com/7987648/74941435-48b1ed80-53f3-11ea-9e6a-fd6f502e4917.png)

**Comment by mateusznitka** [comment]
Hi,
Thanks for ticket.
I know about this problem - it is on my to do list. The reason of that is html2pdf library restrictions. It doesn't have word-breaking or auto-adjust column width, but I have some plans to bypass this.
Regards

**Comment by PeterKarvai-ROEZ** [comment]
Hi,
Thank you for your work. Plugin is very pracical, but it would be awesome to solve this ASAP. 
Thank´s a lot :)

**Comment by mateusznitka** [comment]
Hi, 
It will be the first thing that I'll try to fix. I hope it will be ready within two weeks but I don't promise ;).
Regards

**Comment by PeterKarvai-ROEZ** [comment]
Thank you so mouch

**Comment by mateusznitka** [comment]
Good news, I change pdf library from html2pdf to dompdf and first tests shows that text is wrapping correctly. 
I think update will come in few days.

**Comment by mateusznitka** [comment]
Hi, there is a new update, overflowing problem is resolved, check it out.

Regards,
Mateusz
