### ISSUE TITLE
Use of the rich text editor

### ISSUE THREAD

**Issue by Giudy** [mateusznitka/protocolsmanager#9]
Hi, as in Glpi is used a rich text editor. it could be nice as this plugin could use it

**Comment by mateusznitka** [comment]
Hi,
It is very difficult to implement this feature. I'm using html2pdf library to make PDF from HTML. In your case, it would require to convert RTF to HTML and then to PDF. It would cause a lot of problems according to specific restrictions of HTML to PDF libraries.
Regards
